version: '3'
services:
  api:
    build: .
    #to keep track of changes automatically
    volumes:
      - ./:/usr/src/application:rw
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports :
      - 8000:8000